spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/repository?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Chentyit123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: false
logging:
  level:
    root: info
    cn.chentyit.sdprms.dao: trace
server:
  port: 23333